window.SITE_CONFIG = {
  companyName: "Apex Shield Siding",
  companyLegalName: "Apex Shield Siding LLC",
  companyId: "ID: AS-2048-73",
  website: "www.apexshieldsiding.com",
  websiteUrl: "https://www.apexshieldsiding.com",
  phone: "+15550148260",
  phoneDisplay: "(555) 014-8260",
  phoneButtonLabel: "Call for siding help",
  email: "hello@apexshieldsiding.com",
  addressLine1: "1840 Cedar Ridge Parkway",
  addressLine2: "Suite 210, Columbus, OH 43215",
  serviceArea: "Columbus, Central Ohio, and nearby communities",
  businessHours: "Mon-Fri 7:00 AM-6:00 PM, Sat 8:00 AM-2:00 PM",
  footerTextPrimary: "Complete exterior siding solutions for homeowners who want durable protection, clean curb appeal, and a contractor who manages the full cycle from inspection to final walkthrough.",
  footerTextSecondary: "Independent local siding providers may perform work requested through this website. Verify licensing, insurance, and credentials before hiring any provider.",
  disclaimerShort: "Free siding project guidance connecting homeowners with independent local providers.",
  disclaimerFull: "Disclaimer: This site is a free service to assist users/customers in connecting with local service providers. All contractors/providers are independent and this site does not warrant or guarantee any work performed. It is the responsibility of the customer to verify that the hired contractor/provider furnishes the necessary license, insurance, certification, or other credentials required for the work being performed. All persons depicted in a photo or video are actors or models and not contractors/providers listed on this site.",
  footerDisclaimer: "Apex Shield Siding is an aggregator-style siding inquiry service. Contractors and providers are independent, and no workmanship, pricing, licensing, insurance, timeline, or result is guaranteed by this website.",
  copyrightLine: "All rights reserved.",
  ctaPrimary: "Request a Free Siding Quote",
  ctaSecondary: "Explore Services",
  formSuccessPrefix: "Thanks. Your siding request was received by",
  formSuccessSuffix: "We will respond from"
};
